#!/bin/bash

CONFIGNAME="$1"
shift

PROCMODIFIERS=""
CUSTOMIZE=""
mode=""
echo "" >> temp_custom.py
while [[ $# -gt 0 ]]; do
    case "$1" in
        --procMods) mode="procModifiers" ;;
        --custom) mode="customizations" ;;
        *)
            if [[ "$mode" == "customizations" ]]; then
                cat customizations/$1.py >> temp_custom.py
                echo "" >> temp_custom.py
                echo "" >> temp_custom.py
                CUSTOMIZE="${CUSTOMIZE} $1"
            elif [[ "$mode" == "procModifiers" ]]; then
                PROCMODIFIERS="${PROCMODIFIERS}$1,"
            fi ;;
    esac
    shift
done

PROCMODIFIERS=${PROCMODIFIERS%,}
# CUSTOMIZE=${CUSTOMIZE}


# create the config file without procModifiers
if [ ! "$PROCMODIFIERS" ];then
    #,HLT:75e33_trackingOnly,VALIDATION:@hltValidation
    cmsDriver.py step_2 -s L1P2GT \
         --mc \
         --conditions auto:phase2_realistic_T33 \
         --datatier DQMIO \
         -n -1 \
         --eventcontent DQMIO \
         --geometry ExtendedRun4D110 \
         --era Phase2C17I13M9 \
         --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
         --filein "REPLACEDINPUTFILES" \
         --fileout "Tracking_DQMIO.root" \
         --python_filename "temp_cfg.py" \
         --process SIMPIXELTRACKS \
         --inputCommands='keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT' \
         --no_exec
else
    #,HLT:75e33_trackingOnly,VALIDATION:@hltValidation
    cmsDriver.py step_2 -s L1P2GT \
         --mc \
         --conditions auto:phase2_realistic_T33 \
         --datatier DQMIO \
         -n -1 \
         --eventcontent DQMIO \
         --geometry ExtendedRun4D110 \
         --era Phase2C17I13M9 \
         --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
         --filein "REPLACEDINPUTFILES" \
         --fileout "Tracking_DQMIO.root" \
         --python_filename "temp_cfg.py" \
         --process SIMPIXELTRACKS \
         --inputCommands='keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT' \
         --no_exec \
         --procModifiers $PROCMODIFIERS
fi

# add the config generation command to the beginning of the file
echo '#' | cat - temp_cfg.py > temp && mv temp temp_cfg.py
echo "# ./makeSimPixelTrackConfig.sh $CONFIGNAME --procMods $PROCMODIFIERS --custom$CUSTOMIZE" | cat - temp_cfg.py > temp && mv temp temp_cfg.py
echo '# Autogenerated config file with the following command in Patatrack_configs:' | cat - temp_cfg.py > temp && mv temp temp_cfg.py


# modify the config to allow easy command line options when running cmsRun
python3 scripts/modifySimPixelTrackConfig.py "temp_cfg.py" ${CONFIGNAME} -c temp_custom.py

# delete the temporary config
rm temp_cfg.py
rm temp_custom.py

echo "created config file ${CONFIGNAME}_SIM_cfg.py"
echo "procModifiers: ${PROCMODIFIERS}"
echo "customizations: ${CUSTOMIZE}"