#!/bin/bash

CONFIGNAME="$1"
shift

TIMINGMENU="75e33_timing"
PROCMODIFIERS=""
CUSTOMIZE=""
HLTOPTION=""
mode=""
echo "" >> temp_custom.py
while [[ $# -gt 0 ]]; do
    case "$1" in
        --procMods) mode="procModifiers" ;;
        --custom) mode="customizations" ;;
        --ngt) mode="NGTScouting" 
            TIMINGMENU="NGTScouting"
            HLTOPTION="--ngt"
            ;;
        *)
            if [[ "$mode" == "customizations" ]]; then
                cat customizations/$1.py >> temp_custom.py
                echo "" >> temp_custom.py
                echo "" >> temp_custom.py
                CUSTOMIZE="${CUSTOMIZE} $1"
            elif [[ "$mode" == "procModifiers" ]]; then
                PROCMODIFIERS="${PROCMODIFIERS}$1,"
            fi ;;
    esac
    shift
done

PROCMODIFIERS=${PROCMODIFIERS%,}


# create the config file without procModifiers
if [ ! "$PROCMODIFIERS" ];then
    cmsDriver.py step_2 -s L1P2GT,HLT:$TIMINGMENU \
        --mc \
        --conditions auto:phase2_realistic_T33 \
        -n -1 \
        --eventcontent FEVTDEBUGHLT \
        --geometry ExtendedRun4D110 \
        --era Phase2C17I13M9 \
        --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
         --filein "REPLACEDINPUTFILES" \
         --python_filename "temp_cfg.py" \
        --processName=HLTX \
        --inputCommands="keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT" \
        --no_exec \
        --output={}
else
    cmsDriver.py step_2 -s L1P2GT,HLT:$TIMINGMENU \
        --mc \
        --conditions auto:phase2_realistic_T33 \
        -n -1 \
        --eventcontent FEVTDEBUGHLT \
        --geometry ExtendedRun4D110 \
        --era Phase2C17I13M9 \
        --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
         --filein "REPLACEDINPUTFILES" \
         --python_filename "temp_cfg.py" \
        --processName=HLTX \
        --inputCommands="keep *, drop *_hlt*_*_HLT, drop triggerTriggerFilterObjectWithRefs_l1t*_*_HLT" \
        --no_exec \
        --procModifiers $PROCMODIFIERS \
        --output={}
fi

# add the config generation command to the beginning of the file
echo '#' | cat - temp_cfg.py > temp && mv temp temp_cfg.py
echo "# ./makeTimingConfig.sh $CONFIGNAME --procMods $PROCMODIFIERS --custom$CUSTOMIZE $HLTOPTION" | cat - temp_cfg.py > temp && mv temp temp_cfg.py
echo '# Autogenerated config file with the following command in Patatrack_configs:' | cat - temp_cfg.py > temp && mv temp temp_cfg.py

# make the config directory
mkdir -p timing/${CONFIGNAME}

# modify the config to allow easy command line options when running cmsRun
python3 scripts/modifyTimingConfig.py "temp_cfg.py" "${CONFIGNAME}/${TIMINGMENU}" -c temp_custom.py

# delete the temporary files
rm temp_cfg.py
rm temp_custom.py

echo "created config file timing/${CONFIGNAME}/${TIMINGMENU}_config.py"
echo "procModifiers: ${PROCMODIFIERS}"
echo "customizations: ${CUSTOMIZE}"