## priority for non-skipping doublets in N-tuplet building
def replaceValue(geometry, cut, newValue, inner=None, outer=None):
    """
    Replaces a specific value of a specified vector cut
    
    :param geometry: the geometry parameter set
    :param cut: name of the vector cut
    :param newValue: the new value for this cut and layer pair
    :param inner: inner layer ID
    :param outer: outer layer ID
    """
    for i in range(len(geometry.phiCuts)):
        iLayer = geometry.pairGraph[2*i]
        oLayer = geometry.pairGraph[2*i + 1]
        if ((inner is None) or (iLayer == inner)) and ((outer is None) or (oLayer == outer)):
            setattr(geometry, cut, [(getattr(geometry, cut)[k] if i!=k else newValue) for k in range(len(geometry.phiCuts))])

replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 0, outer= 1)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 0, outer= 2)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 0, outer= 4)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 0, outer= 5)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 0, outer= 6)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 0, outer=16)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 0, outer=17)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 0, outer=18)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 1, outer= 2)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 1, outer= 3)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 1, outer= 4)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 1, outer= 5)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 1, outer= 6)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 1, outer=16)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 1, outer=17)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 1, outer=18)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 1, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 2, outer= 3)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 2, outer= 4)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 2, outer=16)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 2, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 3, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 3, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 4, outer= 5)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 4, outer= 6)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 4, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 4, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 5, outer= 6)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 5, outer= 7)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 5, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 5, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 6, outer= 7)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 6, outer= 8)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 6, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 6, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 7, outer= 8)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 7, outer= 9)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 7, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 7, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 8, outer= 9)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 8, outer=10)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 8, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 8, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 9, outer=10)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner= 9, outer=11)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner= 9, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=10, outer=11)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=10, outer=12)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=11, outer=12)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=11, outer=13)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=11, outer=14)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=11, outer=15)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=12, outer=13)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=13, outer=14)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=14, outer=15)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=16, outer=17)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=16, outer=18)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=16, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=16, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=17, outer=18)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=17, outer=19)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=17, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=17, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=18, outer=19)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=18, outer=20)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=18, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=18, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=19, outer=20)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=19, outer=21)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=19, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=19, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=20, outer=21)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=20, outer=22)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=20, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=20, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=21, outer=22)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=21, outer=23)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=21, outer=28)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=22, outer=23)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=22, outer=24)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=23, outer=24)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=23, outer=25)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=23, outer=26)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=23, outer=27)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=24, outer=25)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=25, outer=26)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=26, outer=27)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=28, outer=29)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int( True), inner=28, outer=30)
replaceValue(process.hltPhase2PixelTracksSoA.geometry, "skipsLayers", int(False), inner=29, outer=30)